- hosts: appServer
  vars:
        srcFolder: /tmp/Spring-PetClinic/target
        destFolder: /tmp/Spring-PetClinic/
  tasks:
  - name: Copy Artefacts from Jenkins to Local
    copy:
        src: "{{ srcFolder }}"
        dest: "{{ destFolder }}"

  - name: Install Java
    shell: yum install java-1.8.0 java-1.8.0-openjdk-devel -y
    become: yes
    
  - name: Start JAR application
    shell: java -jar {{ destFolder }}/target/*.jar &